"""make patronymic nullable

Revision ID: fa1c15f58bca
Revises: 61082e45449a
Create Date: 2026-07-11 12:03:11.174762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1c15f58bca'
down_revision: Union[str, Sequence[str], None] = '61082e45449a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    # ### end Alembic commands ###
